FROM ubuntu:latest

# Install any additional software you need
RUN apt-get update && apt-get install -y git
RUN apt-get install -y curl
RUN apt install -y nodejs
RUN apt install -y npm
RUN npm install --global yarn